version: '3.8'
volumes:
  mongodata: null

services:
  mongodb:
    container_name: mongodb
    entrypoint: /usr/bin/mongod --bind_ip_all --replSet replica-set-platform
    environment:
      MONGO_INITDB_DATABASE: platform
    healthcheck:
      interval: 10s
      start_period: 30s
      test: test $$(echo "rs.initiate({_id:'replica-set-platform',members:[{_id:0,host:\"mongodb:27017\"}]}).ok || rs.status().ok" | mongo --port 27017 --quiet) -eq 1
    image: mongo:4.4.6
    ports:
      - "27017:27017"
    restart: always
    volumes:
      - mongodata:/data/db

  rapid-scrawler:
    container_name: rapid-scrawler
    restart: always
    build:
      dockerfile: Dockerfile
    depends_on:
      mongodb:
        condition: service_healthy
    environment:
      DB_CONN_STR: mongodb://mongodb:27017/
      SCHEDUALER_INTERVAL_SEC: 120
      PARSING_URLS: https://pastebin.com/archive
      NUM_OF_PROCESSES: 1
